<?php

namespace ContainerAzm6b1g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NKYQI6eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nKYQI6e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nKYQI6e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'recipeRepository' => ['privates', '.errored.hCx1mIc', NULL, 'Cannot determine controller argument for "App\\Controller\\HomeController::index()": the $recipeRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\RecipeRepository".'],
        ], [
            'recipeRepository' => '?',
        ]);
    }
}
