<?php

namespace ContainerAzm6b1g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_HCx1mIcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.hCx1mIc' shared service.
     *
     * @return \App\Repository\RecipeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\HomeController::index()": the $recipeRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\RecipeRepository".');
    }
}
