<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWzoxTNt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWzoxTNt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWzoxTNt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWzoxTNt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWzoxTNt\App_KernelDevDebugContainer([
    'container.build_hash' => 'WzoxTNt',
    'container.build_id' => 'd3749fad',
    'container.build_time' => 1676745944,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWzoxTNt');
