<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEGs8xgI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEGs8xgI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEGs8xgI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEGs8xgI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEGs8xgI\App_KernelDevDebugContainer([
    'container.build_hash' => 'EGs8xgI',
    'container.build_id' => 'b6a6acb4',
    'container.build_time' => 1676854843,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEGs8xgI');
