<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZf5T9ML\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZf5T9ML/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZf5T9ML.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZf5T9ML\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZf5T9ML\App_KernelDevDebugContainer([
    'container.build_hash' => 'Zf5T9ML',
    'container.build_id' => '2ada6937',
    'container.build_time' => 1676329678,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZf5T9ML');
